Add #zougla community under News & Politics
snoonetIRC/website pull request #71
Opened 2019-04-11 15:23 UTC by duckspike

2019-04-11 22:32 UTC, linuxdaemon requested changes

2019-04-11 22:32 UTC, linuxdaemon commented on content/community/zougla.md
> +Καλωσήρθατε στο #zougla. Για να συνδεθείτε στο chat, μπείτε στη σελίδα https://chat.zougla.gr/webchat(new tab) και στην συνέχεια πατήστε: Start
I believe this is supposed to be a link

2019-04-11 22:32 UTC, linuxdaemon commented on content/community/zougla.md
> +Το zougla.gr(href blank zougla.gr) κατατάσσεται στις καλύτερες ιστοσελίδες ενημέρωσης στην Ελλάδα, σύμφωνα με το Alexa Rank(new tab https://www.alexa.com/siteinfo/zougla.gr).
Here too

2019-04-11 22:32 UTC, linuxdaemon commented on content/community/zougla.md
> +Οι διαχειριστές/operators του #zougla δεν είναι σε θέση να γνωρίζουν/παρακολουθούν τα προσωπικά σας μηνύματα και επομένως δεν φέρουν καμία ευθύνη για ενδεχόμενες μη νόμιμες ενέργειες σας. Σε περίπτωσ
And here

2019-04-11 22:32 UTC, linuxdaemon commented on content/community/zougla.md
> +a) Όλοι οι χρήστες που συνδέονται στο #zougla(new tab https://chat.zougla.gr/webchat) οφείλουν να διαβάσουν τους κανόνες και την πολιτική λειτουργίας για να γνωρίζουν τι ΔΕΝ πρέπει να κάνουν κατά την
Here

2019-04-11 22:32 UTC, linuxdaemon commented on content/community/zougla.md
> +Θα πρέπει να κάνετε αίτηση γι αυτό στη σελίδα https://chat.zougla.gr/request-oper new tab
here

2019-04-11 22:32 UTC, linuxdaemon commented on content/community/zougla.md
> +Για οποιεσδήποτε ερωτήσεις/καταγγελίες που αφορούν ΜΟΝΟ το #zougla μπορείτε να απευθυνθείτε στο κανάλι #zougla-opers(new tab https://webchat.snoonet.org/#zougla-opers) ή να στείλετε email μέσω της φό
and here

2019-04-12 20:42 UTC, linuxdaemon requested changes

2019-04-12 20:42 UTC, linuxdaemon commented on content/community/zougla.md
> +Το [zougla.gr](http://zougla.gr/) κατατάσσεται στις καλύτερες ιστοσελίδες ενημέρωσης στην Ελλάδα, σύμφωνα με το [Alexa Rank](https://www.alexa.com/siteinfo/zougla.gr)
```suggestion
Το [zougla.gr](https://zougla.gr/) κατατάσσεται στις καλύτερες ιστοσελίδες ενημέρωσης στην Ελλάδα, σύμφωνα με το [Alexa Rank](https://www.alexa.com/siteinfo/zougla.gr)
```

2019-04-12 20:42 UTC, linuxdaemon commented on content/community/zougla.md
> +Μην στέλνετε email για θέματα που αφορούν την κεντρική ιστοσελίδα του [zougla.gr](http://zougla.gr)
```suggestion
Μην στέλνετε email για θέματα που αφορούν την κεντρική ιστοσελίδα του [zougla.gr](https://zougla.gr)
```

2019-04-13 16:49 UTC, linuxdaemon approved these changes

2019-04-14 10:01 UTC, merged

2019-04-15 13:07 UTC, noeatnosleep commented
Somethingsomething GDPR related. Here's the new text they've requested: 

https://acn.gr/d/zougla-texts