Add Git info to pages
snoonetIRC/website pull request #91
Opened 2019-06-06 08:25 UTC by n7st

![2019-06-06-092143_1089x246_scrot](https://user-images.githubusercontent.com/2040110/59017987-c2da1c00-883c-11e9-9163-64e2d75ac499.png)

* Displays on posts & pages.
* Currently doesn't display on "multipage" files (i.e. help, rules) - I think these probably need rethinking (I'll sort that in another branch).
* Doesn't display on the main "Updates" index (because those are summary pages).

2019-06-06 08:26 UTC, n7st commented
Multipage files could have a smaller button linking to the last commit for that particular section.

2019-06-06 15:24 UTC, linuxdaemon requested changes

2019-06-06 15:24 UTC, linuxdaemon commented on themes/Snoonet/layouts/partials/git.html
> +</em>
If you wrap this in `{{with .GitInfo}}` `{{end}}` it should make it so if the git info isn't available, it won't render.

2019-06-08 22:00 UTC, linuxdaemon requested changes
Maybe a label like `last modified` or `updated` would be good? To help show that the page may not have been entirely created by that person, but they were the last to work on it?

2019-06-22 13:09 UTC, linuxdaemon approved these changes

2019-07-03 10:16 UTC, merged