Converted Privacy Policy to Markdown
snoonetIRC/website pull request #93
Opened 2019-06-06 21:55 UTC by nekosune

2019-06-06 21:56 UTC, duckspike approved these changes

2019-06-06 22:30 UTC, linuxdaemon requested changes

2019-06-06 22:30 UTC, linuxdaemon commented on content/privacy-policy.md
> +[Back to Top ](#snoonet-privacy-policy)
```suggestion
{{< back_to_top >}}
```

2019-06-06 22:30 UTC, linuxdaemon commented on content/privacy-policy.md
> +[Back to Top ](#snoonet-privacy-policy)
```suggestion
{{< back_to_top >}}
```

2019-06-06 22:30 UTC, linuxdaemon commented on content/privacy-policy.md
> +[Back to Top ](#snoonet-privacy-policy)
```suggestion
{{< back_to_top >}}
```

2019-06-06 22:30 UTC, linuxdaemon commented on content/privacy-policy.md
> +[Back to Top ](#snoonet-privacy-policy)
```suggestion
{{< back_to_top >}}
```

2019-06-06 22:30 UTC, linuxdaemon commented on content/privacy-policy.md
> +[Back to Top ](#snoonet-privacy-policy)
```suggestion
{{< back_to_top >}}
```

2019-06-06 22:30 UTC, linuxdaemon commented on content/privacy-policy.md
> +[Back to Top ](#snoonet-privacy-policy)
```suggestion
{{< back_to_top >}}
```

2019-06-06 22:30 UTC, linuxdaemon commented on content/privacy-policy.md
> +[Back to Top ](#snoonet-privacy-policy)
```suggestion
{{< back_to_top >}}
```

2019-06-06 22:30 UTC, linuxdaemon commented on content/privacy-policy.md
> +[Back to Top ](#snoonet-privacy-policy)
```suggestion
{{< back_to_top >}}
```

2019-06-06 22:30 UTC, linuxdaemon commented on content/privacy-policy.md
> +[Back to Top ](#snoonet-privacy-policy)
```suggestion
{{< back_to_top >}}
```

2019-06-06 22:30 UTC, linuxdaemon commented on content/privacy-policy.md
> +[Back to Top ](#snoonet-privacy-policy)
```suggestion
{{< back_to_top >}}
```

2019-06-06 22:56 UTC, linuxdaemon approved these changes

2019-06-08 19:05 UTC, n7st approved these changes
I'm merging this now - will take a look on staging and it'll make it into the next release (just want to check the Git info works properly here).

2019-06-08 19:05 UTC, merged